// THIS IS AN AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// You can update it by running `yarn generate-icons-sprite`

export const ICON_NAMES = [
  'play',
  'logo',
  'icon-search',
  'icon-new-window',
  'icon-moon',
  'icon-arrow-down',
] as const

export type IconName = (typeof ICON_NAMES)[number]
